name: Deploy to Firebase Hosting

"on":
    pull_request_review_comment:
        types: [created]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.comment.body == "/deploy" }}

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build:dev
              env:
                  REACT_APP_FIRESTORE_API_KEY: ${{ secrets.REACT_APP_FIRESTORE_API_KEY }}
                  REACT_APP_FIRESTORE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIRESTORE_AUTH_DOMAIN }}
                  REACT_APP_FIRESTORE_PROJECT_ID: ${{ secrets.REACT_APP_FIRESTORE_PROJECT_ID }}
                  REACT_APP_FIRESTORE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIRESTORE_STORAGE_BUCKET }}
                  REACT_APP_FIRESTORE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIRESTORE_MESSAGING_SENDER_ID }}
                  REACT_APP_FIRESTORE_APP_ID: ${{ secrets.REACT_APP_FIRESTORE_APP_ID }}
                  REACT_APP_FIRESTORE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIRESTORE_MEASUREMENT_ID }}

            - name: Deploy to Firebase Hosting - ic-${{ github.actor }}
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ICONTRIBUTE_DEV }}"
                  channelId: live
                  projectId: icontribute-dev
                  target: ic-${{ github.actor }}

            - name: Firebase hosting deploy has succeeded
              if: ${{ success() }}
              uses: actions/github-script@v3
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: "Firebase hosting deploy has succeeded! ✅"
                      })
            - name: Message failure
              if: ${{ failure() }}
              uses: actions/github-script@v4
              with:
                  script: |
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: "Firebase hosting deploy has failed! ❌"
                      })
